### ISSUE TITLE
Incompatibility: arrays of json inside of json files:

### ISSUE THREAD

**Issue by Bjohnson131** [FrenchYann/JSON_for_construct2#2]
JSON with arrays of JSON are incompatible with this plugin. EG:

```
{
"layers":[
        {
         "name":"layer1",
         "data":[...]
        },
        {
         "name:"layer2",
         "data":[...]
        }]
}
```

Please add support.

**Comment by FrenchYann** [comment]
Can't find any issue.

However, your example isn't a valid JSON.
`"name:"layer2"` 
instead of 
`"name":"layer2"`

In the future, you should probably use http://jsonlint.com/ (:

If there's really a problem you should provide a link to a capx

**Comment by danimesq** [comment]
@FrenchYann 
Even with a valid JSON file, this plugin isn't compatible with JSON arrays, as @Bjohnson131 pointed out.

Example:

> {
>   "nextissue": "23",
>   "open": [
>     {
>       "total": "21",
>       "items": [
>         {
>           "0": "1",
>           "1": "2",
>           "2": "4",
>           "3": "5",
>           "4": "6",
>           "5": "7",
>           "6": "8",
>           "7": "9",
>           "8": "10",
>           "9": "11",
>           "10": "12",
>           "11": "13",
>           "12": "14",
>           "13": "15",
>           "14": "16",
>           "15": "17",
>           "16": "18",
>           "17": "19",
>           "18": "20",
>           "19": "21",
>           "20": "22"
>         }
>       ]
>     }
>   ],
>   "closed": [
>     {
>       "total": "1",
>       "items": [
>         {
>           "0": "3"
>         }
>       ]
>     }
>   ]
> }

Using `JSON.Value(0,"open","total")` returns `undefined`, although `JSON.Value(0,"open")` returns `array`.

**Comment by danimesq** [comment]
Have figured out:

Should use `JSON.Value(0,"open",0,"total")` instead, because as there's `{}` inside the `[]` array, it considers the `{}` as another root!

**Comment by FrenchYann** [comment]
Well done figuring it out!

**Comment by Bjohnson131** [comment]
Oh woah, Kudos for giving attention to an issue I wrote way back in my college days!

@FrenchYann  and @danimesq well-done!
