### ISSUE TITLE
inspection.capx gives runtime error

### ISSUE THREAD

**Issue by narFnarF** [FrenchYann/JSON_for_construct2#4]
Loading your inspection.capx that you provide at the bottom of your readme file on github will result in an arror at runtime.

Screenshot of the error:
![image](https://cloud.githubusercontent.com/assets/3538115/18460317/748b56b4-793e-11e6-9471-a952fb25b217.png)

Construct version: r233 (64 bits)

Browser: I tried Chrome and Edge

**Comment by FrenchYann** [comment]
Thanks for the report, I was not handling deprecated expression properly.
And sorry for being so late, I just didn't see the corresponding mail at the time.
